version: '3'
services:
  dnsmasq:
    image: "andyshinn/dnsmasq:latest"
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq.d:/etc/dnsmasq.d
